In [1]:
# import important libraries we will use
import numpy as np
import math
import io
import pandas as pd
from google.colab import files

In [2]:
#updating the xlsx file to here , For your reference and grading, please upload the excel file in the canvas uploaded
uploaded = files.upload()

Saving Data_Assignment1.xlsx to Data_Assignment1.xlsx


In [3]:
# extract the data from the file
xlsx_file = io.BytesIO(uploaded.get('Data_Assignment1.xlsx'))
Q1 = pd.read_excel(xlsx_file, 'question1_Simple_Linear_Reg',header=None)
Q2 = pd.read_excel(xlsx_file, 'question2 Multiple_Linear_Reg',header=None)
Q3 = pd.read_excel(xlsx_file, 'question3_Polynomial Reg',header=None)
Q5 = pd.read_excel(xlsx_file, 'Question5_Metrics')
Q6 = pd.read_excel(xlsx_file, 'question6_Naive Bayes')
print(Q1)
print(Q2)
print(Q3)
print(Q5)
print(Q6)

     0   1
0  1.1  50
1  2.3  55
2  2.9  60
3  4.1  65
4  5.3  75
     0   1    2     3     4
0    1  15  1.3  0.10  0.08
1    2  20  2.0  0.12  0.10
2    3  18  1.8  0.15  0.12
3    4  25  2.5  0.18  0.15
4    5  30  3.0  0.20  0.18
5    6  28  2.8  0.15  0.14
6    7  22  1.7  0.09  0.07
7    8  35  3.5  0.25  0.20
8    9  40  4.0  0.30  0.24
9   10  12  1.2  0.08  0.06
10  11  16  1.6  0.11  0.09
11  12  24  2.1  0.13  0.11
12  13  19  1.9  0.10  0.09
13  14  26  2.2  0.16  0.13
14  15  32  3.2  0.22  0.17
15  16  27  2.9  0.14  0.11
16  17  23  2.3  0.12  0.10
17  18  37  3.7  0.26  0.21
18  19  34  3.4  0.19  0.16
19  20  31  2.7  0.13  0.10
      0      1
0     5  0.003
1    10  0.006
2    15  0.009
3    20  0.014
4    25  0.020
5    30  0.027
6    35  0.036
7    40  0.046
8    45  0.058
9    50  0.072
10   55  0.088
11   60  0.107
12   65  0.128
13   70  0.152
14   75  0.179
15   80  0.210
16   85  0.244
17   90  0.281
18   95  0.322
19  100  0.367
    SampleID  Ground Truth  Pre

Q1

In here, we are given 2 sets of arrays:

X is [50,55,60,65]

Y is [1.1,2,3,2.9,4.1,5.3]

In order to find the best fit we need to get the means of two sets of data first

mean of X = 3.140

mean of Y = 61.0

By alpha closed form, we can get α = 61.8/10.512=5.879

Since Β = mean of y - α(mean of x) = 61.0 - (3.140) * (5.879) = 42.54

y = 5.870 x + 42.54

For the student that studied for 8 hours

y= 89.57

he / she might gets 89.57 as his / her score

Q2

In [4]:
# turn the data in the question 2 as numpy array
q2=np.array(Q2)

In [5]:
# separate the label and the evidence
Y=q2[:,4]
X=q2[:,1:4]
# we add a ones column in the front of the evidence matrix X in order to undergo the multiple regression
ones=np.ones(20)
X= np.insert(X, 0, ones, axis=1)
# print out the X to check whether it works corrrectly
print(X)

[[ 1.   15.    1.3   0.1 ]
 [ 1.   20.    2.    0.12]
 [ 1.   18.    1.8   0.15]
 [ 1.   25.    2.5   0.18]
 [ 1.   30.    3.    0.2 ]
 [ 1.   28.    2.8   0.15]
 [ 1.   22.    1.7   0.09]
 [ 1.   35.    3.5   0.25]
 [ 1.   40.    4.    0.3 ]
 [ 1.   12.    1.2   0.08]
 [ 1.   16.    1.6   0.11]
 [ 1.   24.    2.1   0.13]
 [ 1.   19.    1.9   0.1 ]
 [ 1.   26.    2.2   0.16]
 [ 1.   32.    3.2   0.22]
 [ 1.   27.    2.9   0.14]
 [ 1.   23.    2.3   0.12]
 [ 1.   37.    3.7   0.26]
 [ 1.   34.    3.4   0.19]
 [ 1.   31.    2.7   0.13]]


By the closed form of multiple linear regression
β=(XᵀX)^-1 XᵀY


In [21]:
q2_beta=(np.linalg.inv(np.transpose(X).dot(X)).dot(np.transpose(X))).dot(Y)
print(q2_beta)

[ 1.89524899e-03 -7.46196537e-04  1.16339387e-02  7.47254683e-01]


From the previous codes, we can easily observe that the positive factors are P/B ratio and ROE

Q2 part B

In here we are apply the target data set to the beta value we just get expected return

In [7]:
input=np.array([1,20.1,1.2,0.16])
expected=input.dot(q2_beta)
print(expected)

# From here, we can get a likely 12% of return rate

# testing=np.array([120,88.07,-0.96])
# B=np.array([1,2.8,3])
# print(B.dot(testing))

0.12041817432496604


Q3

In [8]:
# turn the data set into a numpy array
q3=np.array(Q3)
print(Q3)


      0      1
0     5  0.003
1    10  0.006
2    15  0.009
3    20  0.014
4    25  0.020
5    30  0.027
6    35  0.036
7    40  0.046
8    45  0.058
9    50  0.072
10   55  0.088
11   60  0.107
12   65  0.128
13   70  0.152
14   75  0.179
15   80  0.210
16   85  0.244
17   90  0.281
18   95  0.322
19  100  0.367


In [9]:
#seperate the evidences and the labels
train_X=q3[:15,0]
train_Y=q3[:15,1]

# adding a ones columnn in front of the X matrix to do regression
ones_1=np.ones(15)
train_one_X=np.column_stack((ones_1,train_X))

# get the validation sets and do prepocessing like the upper part
validation_X=q3[15:,0]
ones_2=np.ones(5)
validation_Y=q3[15:,1]
validation_one_X= np.column_stack((ones_2,validation_X))


In [10]:
currentX=train_one_X # To store the current X using for training in every degree
currenttX=validation_one_X # To store the current X using for validation in every degree
min_SSR=999999999999999 # storing the minimum SSR
min_beta=np.array([]) # storing the best fit beta
round=0
# we start from the first degree
for i in range (1,60):
  degree=i
  print("Current is number",i)
  if i>1:
    #once the degree is increasing, we modify the X for X for the training and validation
    currentX=np.column_stack((currentX,np.power(train_X,i)))
    currenttX=np.column_stack((currenttX,np.power(validation_X,i)))
  #get the current beta value in this degree
  q3current_beta=(np.linalg.inv(np.transpose(currentX).dot(currentX)).dot(np.transpose(currentX))).dot(train_Y)

  #calculate the SSR for this degree
  currentSSR=np.transpose((validation_Y-currenttX.dot(q3current_beta))).dot((validation_Y-currenttX.dot(q3current_beta)))

  print("Current SSR is",currentSSR)
  #if this degree brings improvement in the SSR, we store the result in this round
  if  currentSSR<min_SSR:
    min_SSR=currentSSR
    min_beta=q3current_beta
    round=i
    print("this is the min beta :",min_beta)
    print("with the shape of :",min_beta.shape)
    print("in degree:",i,'\n')
  else:
    print("No improvement in degree of ",i,'\n')
# give us the best fit degree
print("So in degree ",round," is the best with the beta of :", min_beta, "SSR is :", min_SSR)


Current is number 1
Current SSR is 0.05808195140306123
this is the min beta : [-0.03388571  0.00242214]
with the shape of : (2,)
in degree: 1 

Current is number 2
Current SSR is 0.0036897884769051792
this is the min beta : [ 7.75164835e-03 -5.16965094e-04  3.67388494e-05]
with the shape of : (3,)
in degree: 2 

Current is number 3
Current SSR is 4.334566677415432e-05
this is the min beta : [5.31135531e-04 4.18634035e-04 8.42311283e-06 2.35964471e-07]
with the shape of : (4,)
in degree: 3 

Current is number 4
Current SSR is 1.8169011168441506e-05
this is the min beta : [1.29237429e-03 2.70680853e-04 1.61382821e-05 8.93206094e-08
 9.16524136e-10]
with the shape of : (5,)
in degree: 4 

Current is number 5
Current SSR is 3.114459419212115e-05
No improvement in degree of  5 

Current is number 6
Current SSR is 0.001565987489440626
No improvement in degree of  6 

Current is number 7
Current SSR is 0.01970138469134758
No improvement in degree of  7 

Current is number 8
Current SSR is 0.0

Part B, we can just apply the beta to the inpu to get the answer, but first we have to modify the X of the input to match the degree of 4 which gives us the best fit of this polynomial regression model

In [11]:
# modify the input (76.5)
test=np.array([1,76.5,76.5**2,76.5**3,76.5**4])
expect=test.dot(min_beta)
print(expect)

0.18782318029507283


Q4

In [12]:
# Get the data , in here I assume all of the data given is treated as the input

temp=np.array(q3)
Y_q4=temp[:,1]
X_q4=temp[:,0]

#make the X with 4 degree
ones_q4=np.ones(20)
X_q4=np.column_stack((ones_q4,X_q4))
for i in range(3):
  X_q4=np.column_stack((X_q4,temp[:,0]**(i+2)))
print("The X with degree of 4 with all data is\n",X_q4,"\n")

# add the lamda as 0.01
lamda=0.01
new_beta=(np.linalg.inv(np.transpose(X_q4).dot(X_q4)+(lamda*np.eye(np.transpose(X_q4).dot(X_q4).shape[0]))).dot(np.transpose(X_q4))).dot(Y_q4)
print("So the new beta with all data is ",new_beta,"\n")

# apply the data again
test=np.array([1,76.5,76.5**2,76.5**3,76.5**4])
expect=test.dot(new_beta)
print("The prediction with all data is ",expect)

# in here we are using the training data only
temp=np.array(q3)
Y_q4=temp[:15,1]
X_q4=temp[:15,0]

ones_q4=np.ones(15)
X_q4=np.column_stack((ones_q4,X_q4))
for i in range(3):
  X_q4=np.column_stack((X_q4,temp[:15,0]**(i+2)))
print("The X with degree of 4 with training data is\n",X_q4,"\n")

# add the lamda as 0.01
lamda=0.01
new_beta=(np.linalg.inv(np.transpose(X_q4).dot(X_q4)+(lamda*np.eye(np.transpose(X_q4).dot(X_q4).shape[0]))).dot(np.transpose(X_q4))).dot(Y_q4)
print("So the new beta with training data is ",new_beta,"\n")

# apply the data again
test=np.array([1,76.5,76.5**2,76.5**3,76.5**4])
expect=test.dot(new_beta)
print("The prediction with training data is ",expect)



The X with degree of 4 with all data is
 [[1.0000000e+00 5.0000000e+00 2.5000000e+01 1.2500000e+02 6.2500000e+02]
 [1.0000000e+00 1.0000000e+01 1.0000000e+02 1.0000000e+03 1.0000000e+04]
 [1.0000000e+00 1.5000000e+01 2.2500000e+02 3.3750000e+03 5.0625000e+04]
 [1.0000000e+00 2.0000000e+01 4.0000000e+02 8.0000000e+03 1.6000000e+05]
 [1.0000000e+00 2.5000000e+01 6.2500000e+02 1.5625000e+04 3.9062500e+05]
 [1.0000000e+00 3.0000000e+01 9.0000000e+02 2.7000000e+04 8.1000000e+05]
 [1.0000000e+00 3.5000000e+01 1.2250000e+03 4.2875000e+04 1.5006250e+06]
 [1.0000000e+00 4.0000000e+01 1.6000000e+03 6.4000000e+04 2.5600000e+06]
 [1.0000000e+00 4.5000000e+01 2.0250000e+03 9.1125000e+04 4.1006250e+06]
 [1.0000000e+00 5.0000000e+01 2.5000000e+03 1.2500000e+05 6.2500000e+06]
 [1.0000000e+00 5.5000000e+01 3.0250000e+03 1.6637500e+05 9.1506250e+06]
 [1.0000000e+00 6.0000000e+01 3.6000000e+03 2.1600000e+05 1.2960000e+07]
 [1.0000000e+00 6.5000000e+01 4.2250000e+03 2.7462500e+05 1.7850625e+07]
 [1.000000

Q5

In [13]:
# get the data
print(Q5)

    SampleID  Ground Truth  Prediction
0          1             0           0
1          2             1           0
2          3             0           0
3          4             1           1
4          5             1           0
5          6             0           0
6          7             0           1
7          8             1           1
8          9             1           1
9         10             0           0
10        11             1           1
11        12             0           0
12        13             0           1
13        14             0           0
14        15             1           1
15        16             0           0
16        17             1           0
17        18             1           1
18        19             0           0
19        20             1           1


From the data:

TP=7   

FP=2

FN=3

TN=8



Confusion matrix

                GROUND TRUTH
          PREDICTION TP=7  FP=2
                FN=3  TN=8
  

Accuracy=15/20=0.75

Recall=7/10=0.7

Precision=7/9=0.7778

F1 Score=2*(7/10)(7/9)/(7/10+7/9)=0.7368421

Q6

In [14]:
#data preprocessing : turning the data into numpy
temp=np.array(Q6)
print(temp)

[[ 4.80313855  6.77365833  5.59069655  1.        ]
 [-2.85486012 -2.52636769  0.23216788  2.        ]
 [ 3.89038696  6.17517127  4.67779028  1.        ]
 [ 6.18116604  3.03458129  5.06600934  1.        ]
 [-3.16927832 -4.18685544 -7.59424028  3.        ]
 [-2.63598148 -5.47970158 -3.18777358  3.        ]
 [ 0.28247539  1.15405919 -2.31446951  2.        ]
 [ 5.58644262  3.13487743  4.36421426  1.        ]
 [ 4.15444876  7.02916018  5.78840922  1.        ]
 [ 4.2415467   3.72992861  5.45129021  1.        ]
 [ 4.35098623  5.16681344  6.27084843  1.        ]
 [ 0.36613983 -1.48463183 -0.49355777  2.        ]
 [-0.48879733 -0.39098042  1.27099684  2.        ]
 [ 3.49059528  6.40216229  4.84491961  1.        ]
 [-4.55236814 -5.90825708 -3.69171943  3.        ]
 [ 4.42733513  4.72484276  5.92873605  1.        ]
 [-2.09540518  0.08988914  0.91333417  2.        ]
 [ 5.87587415  3.63225301  5.61212237  1.        ]
 [-4.23706215 -3.96918263 -4.14379557  3.        ]
 [-4.9777478  -4.39422345 -4.80

In [15]:
# Get the labels and evidence
Y_=temp[:,3]
X_=temp[:,:3]
# compute prior probability
P1_=np.count_nonzero(Y_ == 1)/np.count_nonzero(Y_)
P2_=np.count_nonzero(Y_ == 2)/np.count_nonzero(Y_)
P3_=np.count_nonzero(Y_ == 3)/np.count_nonzero(Y_)
print(" the P(C=1) = ",P1_)
print(" the P(C=2) = ",P2_)
print(" the P(C=3) = ",P3_)

 the P(C=1) =  0.4
 the P(C=2) =  0.3
 the P(C=3) =  0.3


In [16]:
# estimate the Gaussian distribution parameters


mean1=np.mean(X_[Y_==1],axis=0)

mean2=np.mean(X_[Y_==2],axis=0)

mean3=np.mean(X_[Y_==3],axis=0)
print("Mean of C=1 is ",mean1)
print("Mean of C=2 is ",mean2)
print("Mean of C=3 is ",mean3)

var1=np.var(X_[Y_==1],axis=0)
var2=np.var(X_[Y_==2],axis=0)
var3=np.var(X_[Y_==3],axis=0)
print("variance of C=1 is ",var1 )
print("variance of C=2 is ",var2 )
print("variance of C=3 is ",var3 )

Mean of C=1 is  [4.83171845 5.09727654 5.40474908]
Mean of C=2 is  [-0.53590249 -0.23939621 -0.02064982]
Mean of C=3 is  [-4.48389755 -4.90847195 -4.77421641]
variance of C=1 is  [0.70220022 2.06440493 0.5094569 ]
variance of C=2 is  [1.39687278 1.46025386 1.11653931]
variance of C=3 is  [2.03523415 0.74354663 1.64959497]


In [17]:
#calculating the Gaussian distribution
def cal( input,mean, var):
  temp=(1/np.sqrt(2*np.pi*var))*np.exp(-(input-mean)**2/(2*var))
  return temp


In [18]:
#using the example in the lecture notes to ensure we get the function correct
tmean=np.array([2.067,1.133])
tvar=np.array([0.042,0.336])
tinput=np.array([2,1.5])
print(cal(tinput,tmean,tvar))

[1.84534051 0.56324165]


In [19]:
#compute the model with the dataset (-5.7,-4.3,-3.34)

input=np.array([-5.7,-4.3,-3.34])

P1=cal(input,mean1,var1)
P2=cal(input,mean2,var2)
P3=cal(input,mean3,var3)

# P(X1= -5.7|C=1)
print("P(X1= -5.7|C=1)is ",P1[0])
# P(X2= -4.3|C=1)
print("P(X2= -4.3|C=1)is ",P1[1])
# P(X3= -3.34C=1)
print("P(X3= -3.34C=1)is ",P1[2])

# P(X1= -5.7|C=2)
print("P(X1= -5.7|C=2)is ",P2[0])
# P(X2= -4.3|C=2)
print("P(X2= -4.3|C=2)is ",P2[1])
# P(X3= -3.34C=2)
print("P(X3= -3.34C=2)is ",P2[2])

# P(X1= -5.7|C=3)
print("P(X1= -5.7|C=3) is ",P3[0])
# P(X2= -4.3|C=3)
print("P(X2= -4.3|C=3) is ",P3[1])
# P(X3= -3.34C=3)
print("P(X3= -3.34C=3) is ",P3[2])


P(X1= -5.7|C=1)is  2.3870417587296927e-35
P(X2= -4.3|C=1)is  1.4276794666453597e-10
P(X3= -3.34C=1)is  1.4225352843821455e-33
P(X1= -5.7|C=2)is  2.4140253144598568e-05
P(X2= -4.3|C=2)is  0.0011661941797579086
P(X3= -3.34C=2)is  0.002717373612051446
P(X1= -5.7|C=3) is  0.194452078115044
P(X2= -4.3|C=3) is  0.3606871628520776
P(X3= -3.34C=3) is  0.16651285803695934


In [20]:
# For C=1 and X=(-5.7,-4.3,-3.34)
# P(C=1|X)=P(C=1)*P(X1|C=1)*P(X2|C=1)*P(X3|C=1)
print("P(C=1|X)=P(C=1)*P(X1|C=1)*P(X2|C=1)*P(X3|C=1) is ",P1_*np.prod(P1))
# P(C=2|X)=P(C=1)*P(X1|C=2)*P(X2|C=2)*P(X3|C=2)
print("P(C=1|X)=P(C=1)*P(X1|C=2)*P(X2|C=2)*P(X3|C=2) is ",P2_*np.prod(P2))
# P(C=3|X)=P(C=3)*P(X1|C=3)*P(X2|C=3)*P(X3|C=3)
print("P(C=3|X)=P(C=3)*P(X1|C=3)*P(X2|C=3)*P(X3|C=3) is ",P3_*np.prod(P3))

result=np.array([P1_*np.prod(P1),P2_*np.prod(P2),P3_*np.prod(P3)])
print("The most likely class is Class ",np.argmax(result)+1)

P(C=1|X)=P(C=1)*P(X1|C=1)*P(X2|C=1)*P(X3|C=1) is  1.939160556013085e-78
P(C=1|X)=P(C=1)*P(X1|C=2)*P(X2|C=2)*P(X3|C=2) is  2.2950032137993337e-11
P(C=3|X)=P(C=3)*P(X1|C=3)*P(X2|C=3)*P(X3|C=3) is  0.0035035821446869823
The most likely class is Class  3
